-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME 
from ANIMAL_OUTS
LEFT JOIN ANIMAL_INS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID 
where ANIMAL_OUTS.SEX_UPON_OUTCOME != ANIMAL_INS.SEX_UPON_INTAKE 
ORDER BY ANIMAL_ID

# INS 보호소에 들어온 동물
# OUTS 입양보낸 동물

# INS엔 중성화 되진 않았찌만
# OUTS 시점엔 중성화 된 동물을 아이디순으로