-- 코드를 입력하세요
SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME from ANIMAL_INS LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID where ANIMAL_OUTS.DATETIME is NULL ORDER BY ANIMAL_INS.DATETIME limit 3

# 입양을 못 간 동물 (ANIMAL_OUTS에 DATETIME 없는 동물) 중 보호소에 오래 있었던 동물